version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sleek_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sleek_ev_db  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: sleek_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine 
    container_name: sleek_rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro

volumes:
  postgres_data: